#!/usr/bin/env bash

set -euo pipefail

declare -Ag LU_PREMADE_PRESET=()

lu_cmd_web_premade_scaffold() {
  local preset="$1"
  local out_dir="${2:-./${preset}}"

  mkdir -p "$out_dir"

  cat >"$out_dir/README.md" <<EOT
# ${preset}

Generated by linuxutils premade webserver scaffolding.

## Quick start
- Inspect files in this folder.
- For static preview: \`python3 -m http.server 8000\`
- Customize as needed.
EOT

  case "$preset" in
    py-flask-*)
      cat >"$out_dir/app.py" <<'EOT'
from flask import Flask
app = Flask(__name__)

@app.get("/")
def home():
    return {"status": "ok", "service": "flask-premade"}

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
EOT
      cat >"$out_dir/requirements.txt" <<'EOT'
flask
EOT
      ;;
    py-fastapi-*)
      cat >"$out_dir/main.py" <<'EOT'
from fastapi import FastAPI
app = FastAPI()

@app.get("/")
def home():
    return {"status": "ok", "service": "fastapi-premade"}
EOT
      cat >"$out_dir/requirements.txt" <<'EOT'
fastapi
uvicorn
EOT
      ;;
    node-express-*)
      cat >"$out_dir/index.js" <<'EOT'
const express = require('express');
const app = express();
app.get('/', (_req, res) => res.json({status: 'ok', service: 'express-premade'}));
app.listen(3000, '0.0.0.0', () => console.log('http://0.0.0.0:3000'));
EOT
      cat >"$out_dir/package.json" <<'EOT'
{
  "name": "express-premade",
  "private": true,
  "version": "0.0.1",
  "main": "index.js",
  "scripts": {"start": "node index.js"},
  "dependencies": {"express": "^4.19.2"}
}
EOT
      ;;
    php-*)
      cat >"$out_dir/index.php" <<'EOT'
<?php
header('Content-Type: application/json');
echo json_encode(['status' => 'ok', 'service' => 'php-premade']);
EOT
      ;;
    go-*)
      cat >"$out_dir/main.go" <<'EOT'
package main

import (
  "fmt"
  "net/http"
)

func main() {
  http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprint(w, `{"status":"ok","service":"go-premade"}`)
  })
  _ = http.ListenAndServe(":8080", nil)
}
EOT
      ;;
    rust-axum-*)
      mkdir -p "$out_dir/src"
      cat >"$out_dir/Cargo.toml" <<'EOT'
[package]
name = "axum-premade"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
EOT
      cat >"$out_dir/src/main.rs" <<'EOT'
use axum::{routing::get, Router};

#[tokio::main]
async fn main() {
    let app = Router::new().route("/", get(|| async { "{\"status\":\"ok\",\"service\":\"axum-premade\"}" }));
    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
EOT
      ;;
    docker-nginx-*|caddy-*|static-*|ws-*)
      mkdir -p "$out_dir/public"
      cat >"$out_dir/public/index.html" <<EOT
<!doctype html>
<html><head><meta charset="utf-8"><title>${preset}</title></head>
<body><h1>${preset}</h1><p>Premade static starter.</p></body></html>
EOT
      cat >"$out_dir/server.sh" <<'EOT'
#!/usr/bin/env bash
set -euo pipefail
python3 -m http.server 8000
EOT
      chmod +x "$out_dir/server.sh"
      ;;
    *)
      mkdir -p "$out_dir/public"
      echo "<h1>${preset}</h1>" > "$out_dir/public/index.html"
      ;;
  esac

  lu_success "Premade scaffold created: $out_dir"
}

lu_cmd_web_premade_dispatch() {
  local key="$1"
  shift
  lu_cmd_web_premade_scaffold "${LU_PREMADE_PRESET[$key]}" "$@"
}

lu_register_premade() {
  local key="$1"
  local preset="$2"
  local desc="$3"
  local example="$4"
  local fn="lu_cmd_${key//./_}"
  fn="${fn//-/_}"

  LU_PREMADE_PRESET["$key"]="$preset"
  eval "${fn}() { lu_cmd_web_premade_dispatch '${key}' \"\$@\"; }"
  register_command "$key" "$desc" "$example" "$fn"
}

stacks=(py-flask py-fastapi node-express php go rust-axum docker-nginx caddy static ws)
modes=(
  blog
  landing
  dashboard
  docs
  status
  admin
  ecommerce
  portfolio
  api
  auth
)

for stack in "${stacks[@]}"; do
  for mode in "${modes[@]}"; do
    preset="${stack}-${mode}"
    key="web.premade-${preset}"
    desc="Generate premade ${stack} ${mode} webserver starter"
    example="linuxutils web premade-${preset} ./premade-${preset}"
    lu_register_premade "$key" "$preset" "$desc" "$example"
  done
done
